name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.x
        node-version:
          - 14.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext-flags: --with-test

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install ocaml-lsp-server
        run: |
          opam pin ocaml-lsp-server https://github.com/ocaml/ocaml-lsp.git --no-action
          opam install ocaml-lsp-server

      - name: Install opam packages
        run: opam install . --deps-only --with-test

      - name: Use latest esy
        run: npm install --global esy

      - name: Install esy packages
        uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Check formatting
        run: yarn fmt:check

      - name: Build extension
        run: opam exec -- make release-build

      - name: Package extension
        run: yarn package

      - name: Upload artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: ocaml-platform-${{ github.sha }}
          path: ocaml-platform.vsix

      - name: Test extension
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test
        env:
          OPAMSWITCH: ${{ github.workspace }}

      - name: Create release
        if: runner.os == 'Linux' && contains(github.ref, 'refs/tags')
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release asset
        if: runner.os == 'Linux' && contains(github.ref, 'refs/tags')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ocaml-platform.vsix
          asset_name: ocaml-platform.vsix
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
